# Generated by Django 2.0.5 on 2018-05-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('univeristy', models.CharField(choices=[('UniMelb', 'University of Melbourne'), ('RMIT', 'Royal Melbourne Institute of Technology'), ('Monash', 'Monash University')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
